version: "3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        restart: always
        volumes:
            - ./:/node-app
            - ./node_modules:/node-app/node_modules
        ports:
            - "3001:3000"
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
